# Controls when the workflow will run
on:
  # Allows me to trigger it from the UI
  workflow_dispatch:
  # Triggers the workflow on a push or pull request
  push:
  pull_request:

# This modifies the default permissions granted to GITHUB_TOKEN. 
# This will vary depending on the needs of your workflow. 
permissions:
  contents: read

# Here are the jobs that run for hte workflow
jobs:
  CI-CD_pipeline:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo and setup the env
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm
      - name: Install
        run: npm ci
      # Build the repo
      - name: Build
        run: npm run build
      # If on the main branch deploy the code
      - name: Deploy
       # if: github.ref == 'refs/heads/main'
        run: |
         git config --global user.email "${{ secrets.EMAIL }}"
         git config --global user.name "${{ secrets.USERNAME }}"
         git remote set-url origin https://github.com/Fell67/giftExchange
         git config --list
         npm run deploy
