# Controls when the workflow will run
on:
  # Allows me to trigger it from the UI
  workflow_dispatch:
  # Triggers the workflow on a push or pull request
  push:
    # excludes giftExchangeWebsite
    branches-ignore:    
      - 'giftExchangeWebsite'   
  pull_request:

# This modifies the default permissions granted to GITHUB_TOKEN. 
# This will vary depending on the needs of your workflow. 
permissions:
  contents: read
  pull-requests: read

# Here are the jobs that run for hte workflow
jobs:
  # The type of runner that the job will run on
  runs-on: ubuntu-latest
  # Setup the env
  setUpEnv:
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: 16.13.x
            cache: npm
      - name: Install
          run: npm install
      - name: Show files changed
          run: cat $HOME/files.json
  # Build the repo
  Build:
    steps:
      - name: Build
          run: npm run build
  # If on the main branch deploy to our website
  Deploy:
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy
          run: npm run deploy
