# Controls when the workflow will run
on:
  # Allows me to trigger it from the UI
  workflow_dispatch:
  # Triggers the workflow on a push or pull request
  push:
  pull_request:

# This modifies the default permissions granted to GITHUB_TOKEN. 
# This will vary depending on the needs of your workflow. 
permissions:
  contents: read
  pull-requests: read

# Here are the jobs that run for hte workflow
jobs:
  # Setup the env
  setUpEnv:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm
      - name: Install
        run: npm ci
      - name: ls -a
        run: ls -a
  # Build the repo
  Build:
    needs: setUpEnv
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: pwd
        run: pwd
      - name: ls -a
        run: ls -a
      - name: Build
        run: npm run build
  # If on the main branch deploy to our website
  Deploy:
    needs: Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy
        run: npm run deploy
